#!/bin/bash

# Colors
#RED=$(tput setaf 1)
#NC=$(tput sgr0) # no color
#GREEN=$(tput setaf 2)

ERROR=0

echo "Validating Puppet DSL syntax..."
for i in $(find lamp/ -type f -name "*.pp"); do puppet parser validate $i; done
if [ "$?" -eq 1 ]; then
	echo "ERROR: Puppet parser failed to validate syntax"
	exit 1
else
	echo "Puppet DSL syntax OK"
fi
echo "Validating Ruby syntax..."
for i in $(find lamp/ -type f -name "*.erb"); do echo $i; erb -x -T '-' $i | ruby -c; done
if [ "$?" -eq 1 ]; then
        echo "FAILURE: Ruby syntax error(s) found"
        exit 1
else
	echo "Ruby syntax OK"
fi
if [ "$1" == "--sync" ]; then
	echo "Syncing with /etc/puppet/ ..."
	sudo rsync -av lamp/etc/puppet/ /etc/puppet
fi
